/**
 * Thin HTTP client for the Holded public API (v2).
 *
 * Every request shape here comes from Holded's official reference at
 * https://www.holded.com/es/desarrolladores (read 2026-10-02; the old
 * developers.holded.com host now redirects there):
 *
 *   - Auth:        `Authorization: Bearer <api key>` on every request. The key
 *                  is generated by the account owner in Holded > Ajustes > API
 *                  and carries per-endpoint scopes (403 when one is missing).
 *   - Base URL:    https://api.holded.com
 *   - Taxes:       GET  /api/v2/taxes                      -> { items: Tax[] }
 *                  (scope accounting:taxes.read). `id` is what goes in a line's
 *                  `taxes` array; `amount` is the percentage as a string.
 *   - Contacts:    GET  /api/v2/contacts?code=<NIF>        -> { items: Contact[] }
 *                  ("code": exact NIF/CIF match; scope contacts:contacts.read)
 *                  GET  /api/v2/contacts/search?name=<x>   -> { items, cursor, has_more }
 *                  POST /api/v2/contacts { name, code, vat_number, type, ... } -> { id }
 *                  (scope contacts:contacts.write)
 *   - Invoices:    POST /api/v2/invoices { contact_id, date, items[], number, ... } -> 201 { id }
 *                  GET  /api/v2/invoices/find-by-number?document_number=<n>
 *                       -> { items: [{ id, document_number, ... }], has_more, cursor }
 *                  (scopes sales:invoices.write / sales:invoices.read)
 *                  GET  /api/v2/invoices/{invoiceId}       -> { id, status, draft, ... }
 *                       (status enum: failed completed pending partial cancelled)
 *                  POST /api/v2/invoices/{invoiceId}/cancel -> 200, no body needed;
 *                       422 when the invoice's state does not allow it ("p. ej.
 *                       ya cobrada o anulada"). Scope sales:invoices.write.
 *                       (read 2026-10-03)
 *   - Errors:     JSON problem details { type, title, status, detail }.
 *                  429 carries Retry-After (seconds).
 *
 * This file is the only place that knows URLs and field names, so if Holded
 * changes its API the blast radius is one file. It never decides anything
 * (which contact, which tax): that lives in HoldedAdapter.
 */

export const HOLDED_API_BASE = "https://api.holded.com";

/** Minimal fetch signature so specs can inject a mock transport. */
export type FetchLike = (
  url: string,
  init: { method: string; headers: Record<string, string>; body?: string; signal?: AbortSignal },
) => Promise<{
  ok: boolean;
  status: number;
  headers: { get(name: string): string | null };
  text(): Promise<string>;
}>;

export interface HoldedTax {
  id: string;
  name?: string | null;
  /** Percentage as a string, e.g. "21". */
  amount?: string | null;
  scope?: string | null;
  key?: string | null;
  group?: string | null;
  type?: string | null;
  status?: boolean | null;
}

export interface HoldedContact {
  id: string;
  name?: string | null;
  code?: string | null;
  vat_number?: string | null;
}

export interface HoldedInvoiceMatch {
  id: string;
  document_number?: string | null;
}

export interface HoldedInvoiceState {
  id: string;
  /** failed | completed | pending | partial | cancelled */
  status?: string | null;
  draft?: boolean | null;
}

export interface HoldedCreateContactBody {
  name: string;
  code?: string | null;
  vat_number?: string | null;
  is_person?: boolean;
  email?: string | null;
  type?: "client";
}

export interface HoldedInvoiceItem {
  name: string;
  description?: string | null;
  units: number;
  /** Unit price before tax. */
  price: number;
  /** Line discount, percentage. */
  discount?: number | null;
  /** Holded tax ids (HoldedTax.id). */
  taxes: string[];
}

export interface HoldedCreateInvoiceBody {
  contact_id: string;
  contact_name?: string;
  /** ISO date YYYY-MM-DD. */
  date: string;
  /** Custom document number: we send the salon's own series + number. */
  number?: string;
  currency?: string;
  notes?: string | null;
  items: HoldedInvoiceItem[];
}

/**
 * A failed Holded call. `status` is 0 for network errors and timeouts, which
 * are as transient as a 5xx.
 */
export class HoldedApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly detail: string,
    public readonly retryAfterSeconds?: number,
  ) {
    super(status ? `Holded HTTP ${status}: ${detail}` : `Holded unreachable: ${detail}`);
  }

  /** Worth retrying later without anyone changing anything. */
  get transient(): boolean {
    return this.status === 0 || this.status === 429 || this.status >= 500;
  }

  /** The key is wrong, revoked or lacks a scope: only the salon can fix it. */
  get credentialProblem(): boolean {
    return this.status === 401 || this.status === 403;
  }
}

const TIMEOUT_MS = 15_000;

export class HoldedClient {
  constructor(
    private readonly apiKey: string,
    private readonly fetchImpl: FetchLike = fetch as unknown as FetchLike,
    private readonly baseUrl: string = HOLDED_API_BASE,
  ) {}

  async listTaxes(): Promise<HoldedTax[]> {
    const res = await this.request<{ items?: HoldedTax[] }>("GET", "/api/v2/taxes");
    return res.items ?? [];
  }

  /**
   * Cheap read probes used when the salon pastes its key, so a key without
   * the contacts or invoices scope is caught at connect time rather than on
   * the first invoice. (Write scopes cannot be probed without writing.)
   */
  async probeContactsRead(): Promise<void> {
    await this.request("GET", `/api/v2/contacts?${new URLSearchParams({ limit: "1" })}`);
  }

  async probeInvoicesRead(): Promise<void> {
    await this.request("GET", `/api/v2/invoices?${new URLSearchParams({ limit: "1" })}`);
  }

  async findContactsByNif(nif: string): Promise<HoldedContact[]> {
    const res = await this.request<{ items?: HoldedContact[] }>(
      "GET",
      `/api/v2/contacts?${new URLSearchParams({ code: nif, limit: "5" })}`,
    );
    return res.items ?? [];
  }

  async searchContactsByName(name: string): Promise<HoldedContact[]> {
    const res = await this.request<{ items?: HoldedContact[] }>(
      "GET",
      `/api/v2/contacts/search?${new URLSearchParams({ name, limit: "25" })}`,
    );
    return res.items ?? [];
  }

  async createContact(body: HoldedCreateContactBody): Promise<{ id: string }> {
    return this.requireId(await this.request<{ id?: string }>("POST", "/api/v2/contacts", body));
  }

  async findInvoicesByNumber(documentNumber: string): Promise<HoldedInvoiceMatch[]> {
    const res = await this.request<{ items?: HoldedInvoiceMatch[] }>(
      "GET",
      `/api/v2/invoices/find-by-number?${new URLSearchParams({ document_number: documentNumber, limit: "50" })}`,
    );
    return res.items ?? [];
  }

  async createInvoice(body: HoldedCreateInvoiceBody): Promise<{ id: string }> {
    return this.requireId(await this.request<{ id?: string }>("POST", "/api/v2/invoices", body));
  }

  async getInvoice(invoiceId: string): Promise<HoldedInvoiceState> {
    return this.request<HoldedInvoiceState>("GET", `/api/v2/invoices/${encodeURIComponent(invoiceId)}`);
  }

  async cancelInvoice(invoiceId: string): Promise<void> {
    await this.request("POST", `/api/v2/invoices/${encodeURIComponent(invoiceId)}/cancel`);
  }

  private requireId(res: { id?: string }): { id: string } {
    if (!res?.id || typeof res.id !== "string") {
      // A 2xx without an id is not a success we can record: storing a
      // made-up id is exactly what this integration used to do.
      throw new HoldedApiError(502, "Holded answered without a document id");
    }
    return { id: res.id };
  }

  private async request<T>(method: "GET" | "POST", path: string, body?: unknown): Promise<T> {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${this.apiKey}`,
      Accept: "application/json",
    };
    if (body !== undefined) headers["Content-Type"] = "application/json";

    let res: Awaited<ReturnType<FetchLike>>;
    try {
      res = await this.fetchImpl(`${this.baseUrl}${path}`, {
        method,
        headers,
        body: body === undefined ? undefined : JSON.stringify(body),
        signal: AbortSignal.timeout(TIMEOUT_MS),
      });
    } catch (err) {
      throw new HoldedApiError(0, (err as Error).message || "network error");
    }

    const text = await res.text().catch(() => "");
    if (!res.ok) {
      const retryAfter = Number(res.headers.get("retry-after"));
      throw new HoldedApiError(
        res.status,
        problemDetail(text) ?? `HTTP ${res.status}`,
        Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter : undefined,
      );
    }
    if (!text) return {} as T;
    try {
      return JSON.parse(text) as T;
    } catch {
      throw new HoldedApiError(502, "Holded answered with a body that is not JSON");
    }
  }
}

/** Pulls the human message out of a problem-details body, if there is one. */
function problemDetail(text: string): string | undefined {
  if (!text) return undefined;
  try {
    const parsed = JSON.parse(text) as { detail?: unknown; title?: unknown; message?: unknown };
    const msg = parsed.detail ?? parsed.message ?? parsed.title;
    if (typeof msg === "string" && msg.trim()) return msg.trim().slice(0, 500);
  } catch {
    // Not JSON: fall through to the raw text.
  }
  return text.slice(0, 300);
}
