import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";

/**
 * KiraStudio marketing site — Astro config.
 *
 * Output: `static` (zero JS by default, all pages pre-rendered to
 * HTML at build time). Cloudflare Pages serves the resulting
 * `dist/` directory as static files. The free tier covers unlimited
 * bandwidth and unlimited requests.
 *
 * Sitemap: generated by `@astrojs/sitemap` from the `pages/`
 * directory at build time. Output is `sitemap-index.xml` + per-page
 * entries at the site origin. The login page is excluded (it's a
 * one-hop redirect; no SEO value).
 *
 * The `@astrojs/check` integration powers `npm run check` for
 * type-checking `.astro` files against this tsconfig.
 */
export default defineConfig({
  output: "static",
  site: "https://marketing.kirastudio.com",
  trailingSlash: "never",
  compressHTML: true,
  build: {
    inlineStylesheets: "auto",
  },
  integrations: [
    sitemap({
      filter: (page) =>
        !page.includes("/login") && !page.includes("/404"),
    }),
  ],
  vite: {
    build: {
      cssMinify: "lightningcss",
    },
  },
});