#!/usr/bin/env bash
#
# quick-deploy.sh -- one-shot deploy of KiraRoom via SSH on the VPS.
#
# What it does:
#   1. Cleans up any stale state left by Hostinger Docker Manager
#      (the kiraroom_* containers, networks, and /docker/kiraroom dir).
#   2. Clones the repo to /opt/kiraroom (idempotent: reuses existing
#      clone if present, otherwise clones fresh).
#   3. Generates three strong secrets locally with openssl
#      (POSTGRES_PASSWORD, JWT_SECRET, OAUTH_STATE_SECRET).
#   4. Writes /opt/kiraroom/.env with the secrets + the Stripe/MiniMax
#      values you provide as env vars to the SSH session.
#   5. Runs `docker compose up -d` against docker-compose.prod.yml.
#   6. Verifies the 5 containers are healthy.
#
# Required env vars to pass via SSH:
#   MINIMAX_API_KEY
#   STRIPE_SECRET_KEY
#   STRIPE_WEBHOOK_SECRET
#   TRAEFIK_NETWORK         (default: root_default)
#   TRAEFIK_ENTRYPOINT_HTTPS (default: websecure)
#   TRAEFIK_CERTRESOLVER    (default: letsencrypt)
#
# Usage from your local PowerShell:
#   ssh root@srv1170607 'bash -s' < ops/deploy/quick-deploy.sh
#
# Or commit this file, push, and run:
#   ssh root@srv1170607 'curl -fsSL https://raw.githubusercontent.com/lagop/KiraRoom/main/ops/deploy/quick-deploy.sh | bash'
#
set -euo pipefail

# ---- 1. Required env vars from caller ---------------------------------
: "${MINIMAX_API_KEY:?Set MINIMAX_API_KEY=<your-key> before running}"
: "${STRIPE_SECRET_KEY:?Set STRIPE_SECRET_KEY=sk_test_... before running}"
: "${STRIPE_WEBHOOK_SECRET:?Set STRIPE_WEBHOOK_SECRET=whsec_... before running}"

TRAEFIK_NETWORK="${TRAEFIK_NETWORK:-root_default}"
TRAEFIK_ENTRYPOINT_HTTPS="${TRAEFIK_ENTRYPOINT_HTTPS:-websecure}"
TRAEFIK_CERTRESOLVER="${TRAEFIK_CERTRESOLVER:-letsencrypt}"

APP_DIR="/opt/kiraroom"
REPO_URL="https://github.com/lagop/KiraRoom.git"

log() { printf '[%s] %s\n' "$(date -u +%H:%M:%SZ)" "$*"; }

# ---- 2. Clean up Hostinger Docker Manager leftovers ------------------
log "Cleaning up Hostinger Docker Manager leftovers (containers, networks, dir)"
docker ps -a --filter "name=kiraroom-" --format '{{.ID}} {{.Names}}' 2>/dev/null \
  | awk '{print $1}' \
  | xargs -r docker rm -f 2>/dev/null || true

# Remove the dedicated networks Hostinger created for this project
for net in kiraroom_default kiraroom_kiraroom-network; do
  if docker network inspect "$net" >/dev/null 2>&1; then
    log "  removing network $net"
    docker network rm "$net" 2>/dev/null || true
  fi
done

# Remove the directory Hostinger used as the compose cwd
if [[ -d "/docker/kiraroom" ]]; then
  log "  removing /docker/kiraroom (Hostinger's old compose dir)"
  rm -rf /docker/kiraroom
fi

# ---- 3. Clone or refresh the repo at /opt/kiraroom ------------------
mkdir -p "$APP_DIR"
if [[ -d "$APP_DIR/.git" ]]; then
  log "Existing clone at $APP_DIR -- fast-forwarding from $REPO_URL"
  (cd "$APP_DIR" && git fetch origin main && git reset --hard origin/main)
else
  log "Cloning $REPO_URL into $APP_DIR"
  rm -rf "$APP_DIR"
  git clone "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

# ---- 4. Generate secrets + write .env -------------------------------
log "Generating fresh POSTGRES_PASSWORD / JWT_SECRET / OAUTH_STATE_SECRET"
POSTGRES_PASSWORD_NEW=$(openssl rand -hex 24)
JWT_SECRET_NEW=$(openssl rand -hex 48)
OAUTH_STATE_SECRET_NEW=$(openssl rand -hex 48)

cat > "$APP_DIR/.env" <<EOF
# Generated by quick-deploy.sh on $(date -u +%FT%TZ)
# DO NOT commit this file (.env is gitignored but explicitly here).

POSTGRES_USER=kiraroom
POSTGRES_PASSWORD=${POSTGRES_PASSWORD_NEW}

JWT_SECRET=${JWT_SECRET_NEW}
OAUTH_STATE_SECRET=${OAUTH_STATE_SECRET_NEW}

MINIMAX_API_KEY=${MINIMAX_API_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

IMAGE_TAG=latest

TRAEFIK_NETWORK=${TRAEFIK_NETWORK}
TRAEFIK_ENTRYPOINT_HTTPS=${TRAEFIK_ENTRYPOINT_HTTPS}
TRAEFIK_CERTRESOLVER=${TRAEFIK_CERTRESOLVER}
EOF
chmod 600 "$APP_DIR/.env"
log "Wrote $APP_DIR/.env (chmod 600)"

# Confirm GHCR login. The previous Hostinger Docker Manager flow
# configured `docker login ghcr.io` on this VPS already, but be defensive.
if ! docker pull ghcr.io/lagop/kiraroom-backend:latest >/dev/null 2>&1; then
  log "GHCR pull failed -- the VPS is not logged into ghcr.io. Run:"
  log "    docker login ghcr.io -u lagop"
  log "  with a fine-grained PAT that has 'Packages: Read-only' scope,"
  log "  then re-run this script."
  exit 1
fi

# ---- 5. Launch the stack ------------------------------------------
log "Bringing the stack up"
docker compose -p kiraroom \
  -f "$APP_DIR/docker-compose.prod.yml" \
  --env-file "$APP_DIR/.env" \
  up -d

# ---- 6. Verify -------------------------------------------------------
log "Waiting up to 90s for backend healthcheck"
elapsed=0
healthy=0
while (( elapsed < 90 )); do
  status=$(docker inspect --format='{{.State.Health.Status}}' kiraroom-backend-prod 2>/dev/null || echo "starting")
  log "  backend health: $status"
  [[ "$status" == "healthy" ]] && { healthy=1; break; }
  sleep 5
  elapsed=$(( elapsed + 5 ))
done

if (( !healthy )); then
  log "Backend did not become healthy in 90s. Tail of logs:"
  docker logs kiraroom-backend-prod --tail=80 2>&1 || true
  log "Inspect env vars with: docker compose -p kiraroom -f $APP_DIR/docker-compose.prod.yml config"
  exit 1
fi

log "All containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" \
  --filter "name=kiraroom-" 2>/dev/null

log "Done. Next deploys: cd $APP_DIR && git pull && docker compose -p kiraroom -f docker-compose.prod.yml --env-file .env up -d"
